from sqlalchemy import create_engine

db_string = "postgres://keujsruvqpelne:291827d8388be8155c772e76b509b9f4e" \
            "f0e9e81b2aef479644628d60aa11c9b@ec2-54-83-205-27.compute-1.amazonaws.com:5432/d9l9fi89u8dmua"

db = create_engine(db_string)

db.execute("CREATE TABLE IF NOT EXISTS users (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
           "username text, password text)")
